/** Google Ads domain — import from @/lib/google-ads/<area>/... */
export * as accounts from '@/lib/google-ads/accounts/accounts'
export * as auth from '@/lib/google-ads/auth/context'
export * as api from '@/lib/google-ads/api/api'
export * as oauth from '@/lib/google-ads/oauth/oauth'
export * as campaign from '@/lib/google-ads/campaign/sync/index'
export * as keyword from './keyword/index'
export * as serviceAccount from '@/lib/google-ads/service-account/service-account'
export * as settings from '@/lib/google-ads/settings/settings-store'
export * as common from '@/lib/google-ads/common/resource-name'
export * as policy from '@/lib/google-ads/policy/policy-guard'
export * as conversion from '@/lib/google-ads/conversion/conversion-goals'
export * as accountDelete from '@/lib/google-ads/account-delete'
export { createGoogleAdsLogger } from './common/logger'
export type { GoogleAdsLogFields, GoogleAdsLogScope } from './common/logger'
