/**
 * 广告元素生成的多语言指令
 * 用于标题、描述等文本元素的生成
 */

export interface LanguageInstructionSet {
  intro: string
  productInfo: string
  productName: string
  brand: string
  unknown: string
  rating: string
  reviews: string
  aboutItem: string
  features: string
  notProvided: string
  keywords: string
  searchVolume: string
  requirements: string
  req1: string
  req2: string
  req3: string
  req4: string
  req5: string
  req6: string
  outputFormat: string
  strictFormat: string
}

export const HEADLINE_LANGUAGE_INSTRUCTIONS: Record<string, LanguageInstructionSet> = {
  'English': {
    intro: 'You are a professional Google Ads copywriter. Based on the following product information, generate 15 Google Search ad headlines.',
    productInfo: 'Product Information:',
    productName: 'Product Name',
    brand: 'Brand',
    unknown: 'Unknown',
    rating: 'Rating',
    reviews: 'reviews',
    aboutItem: 'About this item',
    features: 'Product Features',
    notProvided: 'Not provided',
    keywords: 'High-Volume Keywords:',
    searchVolume: 'Search Volume',
    requirements: 'Requirements:',
    req1: '1. Generate 15 headlines, each with a maximum of 30 characters (including spaces)',
    req2: '2. First 3 headlines must include brand name and core product name (e.g., "Teslong Inspection Camera")',
    req3: '3. Middle 5 headlines should incorporate high-volume keywords',
    req4: '4. Last 7 headlines should emphasize product features, benefits, promotions',
    req5: '5. Use high-intent purchase language (buy, shop, official, store, sale, discount, etc.)',
    req6: '6. Avoid using DKI dynamic insertion syntax',
    outputFormat: 'Output Format (JSON):',
    strictFormat: 'Please strictly follow JSON format and ensure 15 headlines.'
  },

  'German': {
    intro: 'Sie sind ein professioneller Google Ads-Texter. Basierend auf den folgenden Produktinformationen generieren Sie 15 Google-Suchanzeigen-Überschriften.',
    productInfo: 'Produktinformationen:',
    productName: 'Produktname',
    brand: 'Marke',
    unknown: 'Unbekannt',
    rating: 'Bewertung',
    reviews: 'Bewertungen',
    aboutItem: 'Über diesen Artikel',
    features: 'Produktmerkmale',
    notProvided: 'Nicht angegeben',
    keywords: 'Hochvolumen-Keywords:',
    searchVolume: 'Suchvolumen',
    requirements: 'Anforderungen:',
    req1: '1. Generieren Sie 15 Überschriften mit jeweils maximal 30 Zeichen (einschließlich Leerzeichen)',
    req2: '2. Die ersten 3 Überschriften müssen Markennamen und Kernproduktname enthalten (z. B. "Teslong Inspection Camera")',
    req3: '3. Die mittleren 5 Überschriften sollten hochvolumige Keywords enthalten',
    req4: '4. Die letzten 7 Überschriften sollten Produktmerkmale, Vorteile und Aktionen hervorheben',
    req5: '5. Verwenden Sie kaufintensiven Wortschatz (kaufen, shop, offiziell, store, sale, rabatt usw.)',
    req6: '6. Vermeiden Sie die Verwendung von DKI-Dynamik-Syntax',
    outputFormat: 'Ausgabeformat (JSON):',
    strictFormat: 'Bitte halten Sie sich strikt an das JSON-Format und stellen Sie 15 Überschriften sicher.'
  },

  'Chinese': {
    intro: '你是专业的Google Ads文案专家。请基于以下商品信息，生成15个Google搜索广告标题（Headlines）。',
    productInfo: '商品信息：',
    productName: '商品名称',
    brand: '品牌',
    unknown: '未知',
    rating: '评分',
    reviews: '条评价',
    aboutItem: '商品详情',
    features: '商品特性',
    notProvided: '未提供',
    keywords: '高搜索量关键词：',
    searchVolume: '搜索量',
    requirements: '要求：',
    req1: '1. 生成15个标题，每个标题最多30个字符（包括空格）',
    req2: '2. 前3个标题必须包含品牌名称和核心产品名称（例如："Teslong Inspection Camera"）',
    req3: '3. 中间5个标题应该包含高搜索量关键词',
    req4: '4. 最后7个标题应该强调产品特性、优势、促销信息',
    req5: '5. 使用高购买意图的语言（购买、商店、官方、销售、折扣等）',
    req6: '6. 避免使用DKI动态插入语法',
    outputFormat: '输出格式（JSON）：',
    strictFormat: '请严格遵循JSON格式，确保15个标题。'
  },

  'Japanese': {
    intro: 'あなたはプロフェッショナルなGoogle広告コピーライターです。以下の商品情報に基づいて、15個のGoogle検索広告見出しを生成してください。',
    productInfo: '商品情報：',
    productName: '商品名',
    brand: 'ブランド',
    unknown: '不明',
    rating: '評価',
    reviews: 'レビュー',
    aboutItem: 'この商品について',
    features: '商品の特徴',
    notProvided: '提供されていません',
    keywords: '高検索ボリュームキーワード：',
    searchVolume: '検索ボリューム',
    requirements: '要件：',
    req1: '1. 15個の見出しを生成し、各見出しは最大30文字（スペース含む）',
    req2: '2. 最初の3つの見出しはブランド名とコア製品名を含める必要があります（例：「Teslong Inspection Camera」）',
    req3: '3. 中間の5つの見出しは高検索ボリュームキーワードを組み込む必要があります',
    req4: '4. 最後の7つの見出しは製品の特徴、利点、プロモーションを強調する必要があります',
    req5: '5. 高い購買意図の言語を使用してください（購入、ショップ、公式、販売、割引など）',
    req6: '6. DKI動的挿入構文の使用を避けてください',
    outputFormat: '出力形式（JSON）：',
    strictFormat: 'JSONフォーマットを厳密に守り、15個の見出しを確保してください。'
  },

  'Italian': {
    intro: 'Sei un copywriter professionista di Google Ads. Sulla base delle seguenti informazioni sul prodotto, genera 15 titoli di annunci di ricerca Google.',
    productInfo: 'Informazioni sul prodotto:',
    productName: 'Nome del prodotto',
    brand: 'Marca',
    unknown: 'Sconosciuto',
    rating: 'Valutazione',
    reviews: 'recensioni',
    aboutItem: 'Informazioni su questo articolo',
    features: 'Caratteristiche del prodotto',
    notProvided: 'Non fornito',
    keywords: 'Parole chiave ad alto volume:',
    searchVolume: 'Volume di ricerca',
    requirements: 'Requisiti:',
    req1: '1. Genera 15 titoli, ciascuno con un massimo di 30 caratteri (inclusi gli spazi)',
    req2: '2. I primi 3 titoli devono includere il nome del marchio e il nome del prodotto principale (ad es. "Teslong Inspection Camera")',
    req3: '3. I 5 titoli centrali dovrebbero incorporare parole chiave ad alto volume',
    req4: '4. Gli ultimi 7 titoli dovrebbero enfatizzare le caratteristiche del prodotto, i vantaggi, le promozioni',
    req5: '5. Utilizza un linguaggio ad alto intento di acquisto (acquista, negozio, ufficiale, vendita, sconto, ecc.)',
    req6: '6. Evita di utilizzare la sintassi di inserimento dinamico DKI',
    outputFormat: 'Formato di output (JSON):',
    strictFormat: 'Si prega di seguire rigorosamente il formato JSON e assicurare 15 titoli.'
  },

  'Korean': {
    intro: '당신은 전문적인 Google 광고 카피라이터입니다. 다음 제품 정보를 기반으로 15개의 Google 검색 광고 제목을 생성하세요.',
    productInfo: '제품 정보:',
    productName: '제품명',
    brand: '브랜드',
    unknown: '알 수 없음',
    rating: '평점',
    reviews: '리뷰',
    aboutItem: '이 항목 정보',
    features: '제품 특징',
    notProvided: '제공되지 않음',
    keywords: '높은 검색량 키워드:',
    searchVolume: '검색량',
    requirements: '요구사항:',
    req1: '1. 15개의 제목을 생성하며, 각 제목은 최대 30자(공백 포함)',
    req2: '2. 처음 3개의 제목은 브랜드명과 핵심 제품명을 포함해야 함 (예: "Teslong Inspection Camera")',
    req3: '3. 중간 5개의 제목은 높은 검색량 키워드를 포함해야 함',
    req4: '4. 마지막 7개의 제목은 제품 특징, 이점, 프로모션을 강조해야 함',
    req5: '5. 높은 구매 의도 언어 사용 (구매, 상점, 공식, 판매, 할인 등)',
    req6: '6. DKI 동적 삽입 구문 사용 피하기',
    outputFormat: '출력 형식 (JSON):',
    strictFormat: 'JSON 형식을 엄격히 따르고 15개의 제목을 확보하세요.'
  },

  'French': {
    intro: 'Vous êtes un rédacteur professionnel de Google Ads. Sur la base des informations produit suivantes, générez 15 titres d\'annonces de recherche Google.',
    productInfo: 'Informations sur le produit:',
    productName: 'Nom du produit',
    brand: 'Marque',
    unknown: 'Inconnu',
    rating: 'Évaluation',
    reviews: 'avis',
    aboutItem: 'À propos de cet article',
    features: 'Caractéristiques du produit',
    notProvided: 'Non fourni',
    keywords: 'Mots-clés à haut volume:',
    searchVolume: 'Volume de recherche',
    requirements: 'Exigences:',
    req1: '1. Générez 15 titres, chacun avec un maximum de 30 caractères (espaces inclus)',
    req2: '2. Les 3 premiers titres doivent inclure le nom de la marque et le nom du produit principal (par exemple, "Teslong Inspection Camera")',
    req3: '3. Les 5 titres du milieu doivent incorporer des mots-clés à haut volume',
    req4: '4. Les 7 derniers titres doivent mettre l\'accent sur les caractéristiques du produit, les avantages, les promotions',
    req5: '5. Utilisez un langage à forte intention d\'achat (acheter, magasin, officiel, vente, remise, etc.)',
    req6: '6. Évitez d\'utiliser la syntaxe d\'insertion dynamique DKI',
    outputFormat: 'Format de sortie (JSON):',
    strictFormat: 'Veuillez suivre strictement le format JSON et assurer 15 titres.'
  },

  'Spanish': {
    intro: 'Eres un redactor profesional de Google Ads. Basándote en la siguiente información del producto, genera 15 títulos de anuncios de búsqueda de Google.',
    productInfo: 'Información del producto:',
    productName: 'Nombre del producto',
    brand: 'Marca',
    unknown: 'Desconocido',
    rating: 'Calificación',
    reviews: 'reseñas',
    aboutItem: 'Acerca de este artículo',
    features: 'Características del producto',
    notProvided: 'No proporcionado',
    keywords: 'Palabras clave de alto volumen:',
    searchVolume: 'Volumen de búsqueda',
    requirements: 'Requisitos:',
    req1: '1. Genera 15 títulos, cada uno con un máximo de 30 caracteres (incluidos espacios)',
    req2: '2. Los primeros 3 títulos deben incluir el nombre de la marca y el nombre del producto principal (por ejemplo, "Teslong Inspection Camera")',
    req3: '3. Los 5 títulos del medio deben incorporar palabras clave de alto volumen',
    req4: '4. Los últimos 7 títulos deben enfatizar características del producto, beneficios, promociones',
    req5: '5. Utiliza lenguaje de alta intención de compra (comprar, tienda, oficial, venta, descuento, etc.)',
    req6: '6. Evita usar la sintaxis de inserción dinámica DKI',
    outputFormat: 'Formato de salida (JSON):',
    strictFormat: 'Por favor, sigue estrictamente el formato JSON y asegura 15 títulos.'
  },

  'Portuguese': {
    intro: 'Você é um redator profissional de Google Ads. Com base nas seguintes informações do produto, gere 15 títulos de anúncios de pesquisa do Google.',
    productInfo: 'Informações do produto:',
    productName: 'Nome do produto',
    brand: 'Marca',
    unknown: 'Desconhecido',
    rating: 'Classificação',
    reviews: 'avaliações',
    aboutItem: 'Sobre este item',
    features: 'Características do produto',
    notProvided: 'Não fornecido',
    keywords: 'Palavras-chave de alto volume:',
    searchVolume: 'Volume de pesquisa',
    requirements: 'Requisitos:',
    req1: '1. Gere 15 títulos, cada um com no máximo 30 caracteres (incluindo espaços)',
    req2: '2. Os primeiros 3 títulos devem incluir o nome da marca e o nome do produto principal (por exemplo, "Teslong Inspection Camera")',
    req3: '3. Os 5 títulos do meio devem incorporar palavras-chave de alto volume',
    req4: '4. Os últimos 7 títulos devem enfatizar características do produto, benefícios, promoções',
    req5: '5. Use linguagem de alta intenção de compra (comprar, loja, oficial, venda, desconto, etc.)',
    req6: '6. Evite usar a sintaxe de inserção dinâmica DKI',
    outputFormat: 'Formato de saída (JSON):',
    strictFormat: 'Por favor, siga rigorosamente o formato JSON e garanta 15 títulos.'
  },

  'Russian': {
    intro: 'Вы профессиональный копирайтер Google Ads. На основе следующей информации о продукте создайте 15 заголовков объявлений поиска Google.',
    productInfo: 'Информация о продукте:',
    productName: 'Название продукта',
    brand: 'Бренд',
    unknown: 'Неизвестно',
    rating: 'Рейтинг',
    reviews: 'отзывы',
    aboutItem: 'Об этом товаре',
    features: 'Характеристики продукта',
    notProvided: 'Не предоставлено',
    keywords: 'Ключевые слова с высоким объемом:',
    searchVolume: 'Объем поиска',
    requirements: 'Требования:',
    req1: '1. Создайте 15 заголовков, каждый максимум 30 символов (включая пробелы)',
    req2: '2. Первые 3 заголовка должны включать название бренда и основное название продукта (например, "Teslong Inspection Camera")',
    req3: '3. Средние 5 заголовков должны содержать ключевые слова с высоким объемом',
    req4: '4. Последние 7 заголовков должны подчеркивать особенности продукта, преимущества, акции',
    req5: '5. Используйте язык с высоким намерением покупки (купить, магазин, официальный, продажа, скидка и т. д.)',
    req6: '6. Избегайте использования синтаксиса динамической вставки DKI',
    outputFormat: 'Формат вывода (JSON):',
    strictFormat: 'Пожалуйста, строго следуйте формату JSON и обеспечьте 15 заголовков.'
  },

  'Arabic': {
    intro: 'أنت كاتب إعلانات احترافي في Google. بناءً على معلومات المنتج التالية، قم بإنشاء 15 عنوان إعلان بحث Google.',
    productInfo: 'معلومات المنتج:',
    productName: 'اسم المنتج',
    brand: 'العلامة التجارية',
    unknown: 'غير معروف',
    rating: 'التقييم',
    reviews: 'تقييمات',
    aboutItem: 'حول هذا العنصر',
    features: 'ميزات المنتج',
    notProvided: 'لم يتم توفيره',
    keywords: 'الكلمات الرئيسية عالية الحجم:',
    searchVolume: 'حجم البحث',
    requirements: 'المتطلبات:',
    req1: '1. قم بإنشاء 15 عنوان، كل منها بحد أقصى 30 حرف (بما في ذلك المسافات)',
    req2: '2. يجب أن تتضمن أول 3 عناوين اسم العلامة التجارية واسم المنتج الأساسي (على سبيل المثال، "Teslong Inspection Camera")',
    req3: '3. يجب أن تتضمن 5 عناوين في المنتصف كلمات رئيسية عالية الحجم',
    req4: '4. يجب أن تؤكد آخر 7 عناوين على ميزات المنتج والفوائد والعروض الترويجية',
    req5: '5. استخدم لغة ذات نية شراء عالية (شراء، متجر، رسمي، بيع، خصم، إلخ)',
    req6: '6. تجنب استخدام بناء جملة الإدراج الديناميكي DKI',
    outputFormat: 'تنسيق الإخراج (JSON):',
    strictFormat: 'يرجى اتباع تنسيق JSON بدقة وضمان 15 عنوان.'
  },

  'Dutch': {
    intro: 'U bent een professionele Google Ads-copywriter. Genereer op basis van de volgende productinformatie 15 koppen voor Google-zoekadvertenties.',
    productInfo: 'Productinformatie:',
    productName: 'Productnaam',
    brand: 'Merk',
    unknown: 'Onbekend',
    rating: 'Beoordeling',
    reviews: 'beoordelingen',
    aboutItem: 'Over dit item',
    features: 'Productkenmerken',
    notProvided: 'Niet verstrekt',
    keywords: 'Trefwoorden met hoog volume:',
    searchVolume: 'Zoekvolume',
    requirements: 'Vereisten:',
    req1: '1. Genereer 15 koppen, elk met maximaal 30 tekens (inclusief spaties)',
    req2: '2. De eerste 3 koppen moeten merknaam en kernnaam van het product bevatten (bijv. "Teslong Inspection Camera")',
    req3: '3. De middelste 5 koppen moeten trefwoorden met hoog volume bevatten',
    req4: '4. De laatste 7 koppen moeten productkenmerken, voordelen en promoties benadrukken',
    req5: '5. Gebruik taal met hoge koopintentie (kopen, winkel, officieel, uitverkoop, korting, enz.)',
    req6: '6. Vermijd het gebruik van DKI dynamische invoeg-syntax',
    outputFormat: 'Uitvoerformaat (JSON):',
    strictFormat: 'Volg strikt het JSON-formaat en zorg voor 15 koppen.'
  },

  'Polish': {
    intro: 'Jesteś profesjonalnym copywriterem Google Ads. Na podstawie poniższych informacji o produkcie wygeneruj 15 nagłówków reklam w wyszukiwarce Google.',
    productInfo: 'Informacje o produkcie:',
    productName: 'Nazwa produktu',
    brand: 'Marka',
    unknown: 'Nieznana',
    rating: 'Ocena',
    reviews: 'opinie',
    aboutItem: 'O tym produkcie',
    features: 'Cechy produktu',
    notProvided: 'Nie podano',
    keywords: 'Słowa kluczowe o wysokiej liczbie wyszukiwań:',
    searchVolume: 'Liczba wyszukiwań',
    requirements: 'Wymagania:',
    req1: '1. Wygeneruj 15 nagłówków, każdy o maksymalnej długości 30 znaków (włącznie ze spacjami)',
    req2: '2. Pierwsze 3 nagłówki muszą zawierać nazwę marki i główną nazwę produktu (np. "Teslong Inspection Camera")',
    req3: '3. Środkowe 5 nagłówków powinno zawierać słowa kluczowe o wysokiej liczbie wyszukiwań',
    req4: '4. Ostatnie 7 nagłówków powinno podkreślać cechy produktu, korzyści, promocje',
    req5: '5. Używaj języka o wysokiej intencji zakupu (kup, sklep, oficjalny, wyprzedaż, rabat itp.)',
    req6: '6. Unikaj używania składni dynamicznego wstawiania DKI',
    outputFormat: 'Format wyjściowy (JSON):',
    strictFormat: 'Proszę ściśle przestrzegać formatu JSON i zapewnić 15 nagłówków.'
  },

  'Swedish': {
    intro: 'Du är en professionell Google Ads-copywriter. Baserat på följande produktinformation, generera 15 rubriker för Google-sökannonser.',
    productInfo: 'Produktinformation:',
    productName: 'Produktnamn',
    brand: 'Varumärke',
    unknown: 'Okänt',
    rating: 'Betyg',
    reviews: 'recensioner',
    aboutItem: 'Om denna artikel',
    features: 'Produktegenskaper',
    notProvided: 'Ej tillhandahållen',
    keywords: 'Nyckelord med hög volym:',
    searchVolume: 'Sökvolym',
    requirements: 'Krav:',
    req1: '1. Generera 15 rubriker, var och en med max 30 tecken (inklusive mellanslag)',
    req2: '2. De första 3 rubrikerna måste innehålla varumärkesnamn och kärnproduktnamn (t.ex. "Teslong Inspection Camera")',
    req3: '3. De mellersta 5 rubrikerna bör innehålla nyckelord med hög volym',
    req4: '4. De sista 7 rubrikerna bör betona produktegenskaper, fördelar, kampanjer',
    req5: '5. Använd språk med hög köpavsikt (köp, butik, officiell, rea, rabatt etc.)',
    req6: '6. Undvik att använda DKI dynamisk infogningssyntax',
    outputFormat: 'Utdataformat (JSON):',
    strictFormat: 'Vänligen följ JSON-format strikt och säkerställ 15 rubriker.'
  },

  'Norwegian': {
    intro: 'Du er en profesjonell Google Ads-tekstforfatter. Basert på følgende produktinformasjon, generer 15 overskrifter for Google-søkeannonser.',
    productInfo: 'Produktinformasjon:',
    productName: 'Produktnavn',
    brand: 'Merke',
    unknown: 'Ukjent',
    rating: 'Vurdering',
    reviews: 'anmeldelser',
    aboutItem: 'Om dette produktet',
    features: 'Produktegenskaper',
    notProvided: 'Ikke oppgitt',
    keywords: 'Nøkkelord med høyt volum:',
    searchVolume: 'Søkevolum',
    requirements: 'Krav:',
    req1: '1. Generer 15 overskrifter, hver med maks 30 tegn (inkludert mellomrom)',
    req2: '2. De første 3 overskriftene må inneholde merkenavn og kjerneproduktnavnet (f.eks. "Teslong Inspection Camera")',
    req3: '3. De midterste 5 overskriftene bør inneholde nøkkelord med høyt volum',
    req4: '4. De siste 7 overskriftene bør fremheve produktegenskaper, fordeler, kampanjer',
    req5: '5. Bruk språk med høy kjøpsintensjon (kjøp, butikk, offisiell, salg, rabatt osv.)',
    req6: '6. Unngå å bruke DKI dynamisk innsettingssyntaks',
    outputFormat: 'Utdataformat (JSON):',
    strictFormat: 'Vennligst følg JSON-format strengt og sikre 15 overskrifter.'
  },

  'Danish': {
    intro: 'Du er en professionel Google Ads-tekstforfatter. Baseret på følgende produktinformation, generer 15 overskrifter til Google-søgeannoncer.',
    productInfo: 'Produktinformation:',
    productName: 'Produktnavn',
    brand: 'Mærke',
    unknown: 'Ukendt',
    rating: 'Bedømmelse',
    reviews: 'anmeldelser',
    aboutItem: 'Om dette produkt',
    features: 'Produktegenskaber',
    notProvided: 'Ikke angivet',
    keywords: 'Nøgleord med høj volumen:',
    searchVolume: 'Søgevolumen',
    requirements: 'Krav:',
    req1: '1. Generer 15 overskrifter, hver med maks 30 tegn (inklusive mellemrum)',
    req2: '2. De første 3 overskrifter skal indeholde mærkenavn og kerneproduktnavnet (f.eks. "Teslong Inspection Camera")',
    req3: '3. De midterste 5 overskrifter skal indeholde nøgleord med høj volumen',
    req4: '4. De sidste 7 overskrifter skal fremhæve produktegenskaber, fordele, kampagner',
    req5: '5. Brug sprog med høj købsintention (køb, butik, officiel, udsalg, rabat osv.)',
    req6: '6. Undgå at bruge DKI dynamisk indsættelsessyntaks',
    outputFormat: 'Outputformat (JSON):',
    strictFormat: 'Følg venligst JSON-format strengt og sikre 15 overskrifter.'
  },

  'Finnish': {
    intro: 'Olet ammattimainen Google Ads -copywriter. Luo seuraavien tuotetietojen perusteella 15 Google-hakumainosten otsikkoa.',
    productInfo: 'Tuotetiedot:',
    productName: 'Tuotenimi',
    brand: 'Brändi',
    unknown: 'Tuntematon',
    rating: 'Arvio',
    reviews: 'arvostelua',
    aboutItem: 'Tästä tuotteesta',
    features: 'Tuotteen ominaisuudet',
    notProvided: 'Ei annettu',
    keywords: 'Korkean volyymin avainsanat:',
    searchVolume: 'Hakuvolyymi',
    requirements: 'Vaatimukset:',
    req1: '1. Luo 15 otsikkoa, joista jokainen on enintään 30 merkkiä (mukaan lukien välilyönnit)',
    req2: '2. Kolmen ensimmäisen otsikon on sisällettävä brändinimi ja ydintuotenimi (esim. "Teslong Inspection Camera")',
    req3: '3. Keskimmäisten 5 otsikon tulisi sisältää korkean volyymin avainsanoja',
    req4: '4. Viimeisten 7 otsikon tulisi korostaa tuotteen ominaisuuksia, etuja, kampanjoita',
    req5: '5. Käytä korkean ostoaikeen kieltä (osta, kauppa, virallinen, ale, alennus jne.)',
    req6: '6. Vältä DKI dynaamisen lisäyksen syntaksia',
    outputFormat: 'Tulostusmuoto (JSON):',
    strictFormat: 'Seuraa tarkasti JSON-muotoa ja varmista 15 otsikkoa.'
  },

  'Thai': {
    intro: 'คุณเป็นนักเขียนโฆษณา Google Ads มืออาชีพ จากข้อมูลผลิตภัณฑ์ต่อไปนี้ สร้างหัวข้อโฆษณา Google Search 15 รายการ',
    productInfo: 'ข้อมูลผลิตภัณฑ์:',
    productName: 'ชื่อผลิตภัณฑ์',
    brand: 'แบรนด์',
    unknown: 'ไม่ทราบ',
    rating: 'คะแนน',
    reviews: 'รีวิว',
    aboutItem: 'เกี่ยวกับสินค้านี้',
    features: 'คุณสมบัติผลิตภัณฑ์',
    notProvided: 'ไม่ได้ระบุ',
    keywords: 'คีย์เวิร์ดที่มีปริมาณการค้นหาสูง:',
    searchVolume: 'ปริมาณการค้นหา',
    requirements: 'ข้อกำหนด:',
    req1: '1. สร้างหัวข้อ 15 รายการ แต่ละรายการไม่เกิน 30 ตัวอักษร (รวมช่องว่าง)',
    req2: '2. หัวข้อ 3 รายการแรกต้องมีชื่อแบรนด์และชื่อผลิตภัณฑ์หลัก (เช่น "Teslong Inspection Camera")',
    req3: '3. หัวข้อ 5 รายการตรงกลางควรมีคีย์เวิร์ดที่มีปริมาณการค้นหาสูง',
    req4: '4. หัวข้อ 7 รายการสุดท้ายควรเน้นคุณสมบัติผลิตภัณฑ์ ประโยชน์ โปรโมชั่น',
    req5: '5. ใช้ภาษาที่มีความตั้งใจซื้อสูง (ซื้อ, ร้าน, ทางการ, ลดราคา, ส่วนลด ฯลฯ)',
    req6: '6. หลีกเลี่ยงการใช้ไวยากรณ์การแทรกแบบไดนามิก DKI',
    outputFormat: 'รูปแบบผลลัพธ์ (JSON):',
    strictFormat: 'กรุณาปฏิบัติตามรูปแบบ JSON อย่างเคร่งครัดและให้แน่ใจว่ามีหัวข้อ 15 รายการ'
  },

  'Vietnamese': {
    intro: 'Bạn là một copywriter quảng cáo Google Ads chuyên nghiệp. Dựa trên thông tin sản phẩm sau đây, hãy tạo 15 tiêu đề quảng cáo tìm kiếm Google.',
    productInfo: 'Thông tin sản phẩm:',
    productName: 'Tên sản phẩm',
    brand: 'Thương hiệu',
    unknown: 'Không rõ',
    rating: 'Đánh giá',
    reviews: 'đánh giá',
    aboutItem: 'Về sản phẩm này',
    features: 'Đặc điểm sản phẩm',
    notProvided: 'Chưa cung cấp',
    keywords: 'Từ khóa có lượng tìm kiếm cao:',
    searchVolume: 'Lượng tìm kiếm',
    requirements: 'Yêu cầu:',
    req1: '1. Tạo 15 tiêu đề, mỗi tiêu đề tối đa 30 ký tự (bao gồm cả khoảng trắng)',
    req2: '2. 3 tiêu đề đầu tiên phải bao gồm tên thương hiệu và tên sản phẩm chính (ví dụ: "Teslong Inspection Camera")',
    req3: '3. 5 tiêu đề ở giữa nên bao gồm từ khóa có lượng tìm kiếm cao',
    req4: '4. 7 tiêu đề cuối cùng nên nhấn mạnh đặc điểm sản phẩm, lợi ích, khuyến mãi',
    req5: '5. Sử dụng ngôn ngữ có ý định mua hàng cao (mua, cửa hàng, chính hãng, giảm giá, khuyến mãi, v.v.)',
    req6: '6. Tránh sử dụng cú pháp chèn động DKI',
    outputFormat: 'Định dạng đầu ra (JSON):',
    strictFormat: 'Vui lòng tuân thủ nghiêm ngặt định dạng JSON và đảm bảo 15 tiêu đề.'
  },

  'Indonesian': {
    intro: 'Anda adalah copywriter Google Ads profesional. Berdasarkan informasi produk berikut, buatlah 15 judul iklan pencarian Google.',
    productInfo: 'Informasi Produk:',
    productName: 'Nama Produk',
    brand: 'Merek',
    unknown: 'Tidak diketahui',
    rating: 'Peringkat',
    reviews: 'ulasan',
    aboutItem: 'Tentang item ini',
    features: 'Fitur Produk',
    notProvided: 'Tidak disediakan',
    keywords: 'Kata kunci dengan volume tinggi:',
    searchVolume: 'Volume Pencarian',
    requirements: 'Persyaratan:',
    req1: '1. Buat 15 judul, masing-masing maksimal 30 karakter (termasuk spasi)',
    req2: '2. 3 judul pertama harus menyertakan nama merek dan nama produk inti (misalnya, "Teslong Inspection Camera")',
    req3: '3. 5 judul di tengah harus memasukkan kata kunci dengan volume tinggi',
    req4: '4. 7 judul terakhir harus menekankan fitur produk, manfaat, promosi',
    req5: '5. Gunakan bahasa dengan niat beli tinggi (beli, toko, resmi, diskon, promo, dll.)',
    req6: '6. Hindari penggunaan sintaks penyisipan dinamis DKI',
    outputFormat: 'Format Output (JSON):',
    strictFormat: 'Harap ikuti format JSON dengan ketat dan pastikan 15 judul.'
  },

  'Turkish': {
    intro: 'Siz profesyonel bir Google Ads metin yazarısınız. Aşağıdaki ürün bilgilerine dayanarak 15 Google Arama reklamı başlığı oluşturun.',
    productInfo: 'Ürün Bilgileri:',
    productName: 'Ürün Adı',
    brand: 'Marka',
    unknown: 'Bilinmiyor',
    rating: 'Değerlendirme',
    reviews: 'yorum',
    aboutItem: 'Bu ürün hakkında',
    features: 'Ürün Özellikleri',
    notProvided: 'Belirtilmedi',
    keywords: 'Yüksek hacimli anahtar kelimeler:',
    searchVolume: 'Arama Hacmi',
    requirements: 'Gereksinimler:',
    req1: '1. Her biri en fazla 30 karakter (boşluklar dahil) olmak üzere 15 başlık oluşturun',
    req2: '2. İlk 3 başlık marka adı ve ana ürün adını içermelidir (örneğin, "Teslong Inspection Camera")',
    req3: '3. Ortadaki 5 başlık yüksek hacimli anahtar kelimeleri içermelidir',
    req4: '4. Son 7 başlık ürün özellikleri, faydaları, promosyonları vurgulamalıdır',
    req5: '5. Yüksek satın alma niyetli dil kullanın (satın al, mağaza, resmi, indirim, kampanya vb.)',
    req6: '6. DKI dinamik ekleme sözdizimi kullanmaktan kaçının',
    outputFormat: 'Çıktı Formatı (JSON):',
    strictFormat: 'Lütfen JSON formatına sıkı sıkıya uyun ve 15 başlık olduğundan emin olun.'
  },

  'Hindi': {
    intro: 'आप एक पेशेवर Google Ads कॉपीराइटर हैं। निम्नलिखित उत्पाद जानकारी के आधार पर, 15 Google खोज विज्ञापन शीर्षक बनाएं।',
    productInfo: 'उत्पाद जानकारी:',
    productName: 'उत्पाद का नाम',
    brand: 'ब्रांड',
    unknown: 'अज्ञात',
    rating: 'रेटिंग',
    reviews: 'समीक्षाएं',
    aboutItem: 'इस आइटम के बारे में',
    features: 'उत्पाद विशेषताएं',
    notProvided: 'प्रदान नहीं किया गया',
    keywords: 'उच्च वॉल्यूम कीवर्ड:',
    searchVolume: 'खोज वॉल्यूम',
    requirements: 'आवश्यकताएं:',
    req1: '1. 15 शीर्षक बनाएं, प्रत्येक अधिकतम 30 अक्षर (स्पेस सहित)',
    req2: '2. पहले 3 शीर्षकों में ब्रांड नाम और मुख्य उत्पाद नाम शामिल होना चाहिए (जैसे, "Teslong Inspection Camera")',
    req3: '3. बीच के 5 शीर्षकों में उच्च वॉल्यूम कीवर्ड शामिल होने चाहिए',
    req4: '4. अंतिम 7 शीर्षकों में उत्पाद विशेषताएं, लाभ, प्रचार पर जोर देना चाहिए',
    req5: '5. उच्च खरीद इरादे वाली भाषा का उपयोग करें (खरीदें, स्टोर, आधिकारिक, सेल, छूट आदि)',
    req6: '6. DKI डायनामिक इंसर्शन सिंटैक्स का उपयोग करने से बचें',
    outputFormat: 'आउटपुट फॉर्मेट (JSON):',
    strictFormat: 'कृपया JSON फॉर्मेट का सख्ती से पालन करें और 15 शीर्षक सुनिश्चित करें।'
  },

  'Greek': {
    intro: 'Είστε επαγγελματίας copywriter Google Ads. Με βάση τις παρακάτω πληροφορίες προϊόντος, δημιουργήστε 15 τίτλους διαφημίσεων αναζήτησης Google.',
    productInfo: 'Πληροφορίες Προϊόντος:',
    productName: 'Όνομα Προϊόντος',
    brand: 'Μάρκα',
    unknown: 'Άγνωστο',
    rating: 'Βαθμολογία',
    reviews: 'κριτικές',
    aboutItem: 'Σχετικά με αυτό το προϊόν',
    features: 'Χαρακτηριστικά Προϊόντος',
    notProvided: 'Δεν παρέχεται',
    keywords: 'Λέξεις-κλειδιά υψηλού όγκου:',
    searchVolume: 'Όγκος Αναζήτησης',
    requirements: 'Απαιτήσεις:',
    req1: '1. Δημιουργήστε 15 τίτλους, κάθε ένας με μέγιστο 30 χαρακτήρες (συμπεριλαμβανομένων κενών)',
    req2: '2. Οι πρώτοι 3 τίτλοι πρέπει να περιλαμβάνουν το όνομα της μάρκας και το κύριο όνομα προϊόντος (π.χ. "Teslong Inspection Camera")',
    req3: '3. Οι μεσαίοι 5 τίτλοι πρέπει να περιλαμβάνουν λέξεις-κλειδιά υψηλού όγκου',
    req4: '4. Οι τελευταίοι 7 τίτλοι πρέπει να τονίζουν χαρακτηριστικά προϊόντος, οφέλη, προσφορές',
    req5: '5. Χρησιμοποιήστε γλώσσα υψηλής πρόθεσης αγοράς (αγορά, κατάστημα, επίσημο, έκπτωση, προσφορά κλπ.)',
    req6: '6. Αποφύγετε τη χρήση σύνταξης δυναμικής εισαγωγής DKI',
    outputFormat: 'Μορφή Εξόδου (JSON):',
    strictFormat: 'Παρακαλώ ακολουθήστε αυστηρά τη μορφή JSON και εξασφαλίστε 15 τίτλους.'
  },

  'Czech': {
    intro: 'Jste profesionální copywriter Google Ads. Na základě následujících informací o produktu vygenerujte 15 nadpisů reklamních inzerátů pro vyhledávání Google.',
    productInfo: 'Informace o produktu:',
    productName: 'Název produktu',
    brand: 'Značka',
    unknown: 'Neznámé',
    rating: 'Hodnocení',
    reviews: 'recenzí',
    aboutItem: 'O tomto produktu',
    features: 'Vlastnosti produktu',
    notProvided: 'Neposkytnuto',
    keywords: 'Klíčová slova s vysokým objemem:',
    searchVolume: 'Objem vyhledávání',
    requirements: 'Požadavky:',
    req1: '1. Vygenerujte 15 nadpisů, každý s maximálně 30 znaky (včetně mezer)',
    req2: '2. První 3 nadpisy musí obsahovat název značky a hlavní název produktu (např. "Teslong Inspection Camera")',
    req3: '3. Prostředních 5 nadpisů by mělo obsahovat klíčová slova s vysokým objemem',
    req4: '4. Posledních 7 nadpisů by mělo zdůrazňovat vlastnosti produktu, výhody, propagační akce',
    req5: '5. Používejte jazyk s vysokým záměrem nákupu (koupit, obchod, oficiální, sleva, akce atd.)',
    req6: '6. Vyhněte se používání syntaxe dynamického vkládání DKI',
    outputFormat: 'Formát výstupu (JSON):',
    strictFormat: 'Dodržujte prosím přísně formát JSON a zajistěte 15 nadpisů.'
  },

  'Hungarian': {
    intro: 'Ön egy professzionális Google Ads szövegíró. Az alábbi termékinformációk alapján hozzon létre 15 Google keresési hirdetés címsort.',
    productInfo: 'Termékinformációk:',
    productName: 'Terméknév',
    brand: 'Márka',
    unknown: 'Ismeretlen',
    rating: 'Értékelés',
    reviews: 'vélemény',
    aboutItem: 'A termékről',
    features: 'Termékjellemzők',
    notProvided: 'Nem megadott',
    keywords: 'Magas keresési volumenű kulcsszavak:',
    searchVolume: 'Keresési volumen',
    requirements: 'Követelmények:',
    req1: '1. Hozzon létre 15 címsort, mindegyik legfeljebb 30 karakter (szóközökkel együtt)',
    req2: '2. Az első 3 címsornak tartalmaznia kell a márkanevet és a fő terméknevet (pl. "Teslong Inspection Camera")',
    req3: '3. A középső 5 címsornak magas volumenű kulcsszavakat kell tartalmaznia',
    req4: '4. Az utolsó 7 címsornak ki kell emelnie a termékjellemzőket, előnyöket, akciókat',
    req5: '5. Használjon magas vásárlási szándékú nyelvet (vásárlás, bolt, hivatalos, akció, kedvezmény stb.)',
    req6: '6. Kerülje a DKI dinamikus beillesztési szintaxis használatát',
    outputFormat: 'Kimeneti formátum (JSON):',
    strictFormat: 'Kérjük, szigorúan tartsa be a JSON formátumot és biztosítson 15 címsort.'
  },

  'Hebrew': {
    intro: 'אתה קופירייטר מקצועי של Google Ads. בהתבסס על המידע הבא על המוצר, צור 15 כותרות מודעות חיפוש Google.',
    productInfo: 'מידע על המוצר:',
    productName: 'שם המוצר',
    brand: 'מותג',
    unknown: 'לא ידוע',
    rating: 'דירוג',
    reviews: 'ביקורות',
    aboutItem: 'על פריט זה',
    features: 'תכונות המוצר',
    notProvided: 'לא סופק',
    keywords: 'מילות מפתח בנפח גבוה:',
    searchVolume: 'נפח חיפוש',
    requirements: 'דרישות:',
    req1: '1. צור 15 כותרות, כל אחת עד 30 תווים (כולל רווחים)',
    req2: '2. 3 הכותרות הראשונות חייבות לכלול את שם המותג ושם המוצר העיקרי (לדוגמה, "Teslong Inspection Camera")',
    req3: '3. 5 הכותרות האמצעיות צריכות לכלול מילות מפתח בנפח גבוה',
    req4: '4. 7 הכותרות האחרונות צריכות להדגיש תכונות מוצר, יתרונות, מבצעים',
    req5: '5. השתמש בשפה עם כוונת קנייה גבוהה (קנה, חנות, רשמי, מכירה, הנחה וכו\')',
    req6: '6. הימנע משימוש בתחביר הכנסה דינמית DKI',
    outputFormat: 'פורמט פלט (JSON):',
    strictFormat: 'אנא עקוב בקפדנות אחר פורמט JSON והבטח 15 כותרות.'
  },

  'Ukrainian': {
    intro: 'Ви професійний копірайтер Google Ads. На основі наступної інформації про продукт створіть 15 заголовків пошукових оголошень Google.',
    productInfo: 'Інформація про продукт:',
    productName: 'Назва продукту',
    brand: 'Бренд',
    unknown: 'Невідомо',
    rating: 'Рейтинг',
    reviews: 'відгуків',
    aboutItem: 'Про цей товар',
    features: 'Характеристики продукту',
    notProvided: 'Не надано',
    keywords: 'Ключові слова з високим обсягом:',
    searchVolume: 'Обсяг пошуку',
    requirements: 'Вимоги:',
    req1: '1. Створіть 15 заголовків, кожен максимум 30 символів (включаючи пробіли)',
    req2: '2. Перші 3 заголовки повинні містити назву бренду та основну назву продукту (наприклад, "Teslong Inspection Camera")',
    req3: '3. Середні 5 заголовків повинні містити ключові слова з високим обсягом',
    req4: '4. Останні 7 заголовків повинні підкреслювати характеристики продукту, переваги, акції',
    req5: '5. Використовуйте мову з високим наміром покупки (купити, магазин, офіційний, знижка, акція тощо)',
    req6: '6. Уникайте використання синтаксису динамічної вставки DKI',
    outputFormat: 'Формат виводу (JSON):',
    strictFormat: 'Будь ласка, суворо дотримуйтесь формату JSON та забезпечте 15 заголовків.'
  },

  'Romanian': {
    intro: 'Sunteți un copywriter profesionist Google Ads. Pe baza următoarelor informații despre produs, generați 15 titluri de anunțuri de căutare Google.',
    productInfo: 'Informații despre produs:',
    productName: 'Numele produsului',
    brand: 'Marcă',
    unknown: 'Necunoscut',
    rating: 'Evaluare',
    reviews: 'recenzii',
    aboutItem: 'Despre acest articol',
    features: 'Caracteristici produs',
    notProvided: 'Nefurnizat',
    keywords: 'Cuvinte cheie cu volum mare:',
    searchVolume: 'Volum de căutare',
    requirements: 'Cerințe:',
    req1: '1. Generați 15 titluri, fiecare cu maximum 30 de caractere (inclusiv spații)',
    req2: '2. Primele 3 titluri trebuie să includă numele mărcii și numele produsului principal (de exemplu, "Teslong Inspection Camera")',
    req3: '3. Cele 5 titluri din mijloc ar trebui să includă cuvinte cheie cu volum mare',
    req4: '4. Ultimele 7 titluri ar trebui să evidențieze caracteristicile produsului, beneficiile, promoțiile',
    req5: '5. Utilizați limbaj cu intenție de cumpărare ridicată (cumpără, magazin, oficial, reducere, promoție etc.)',
    req6: '6. Evitați utilizarea sintaxei de inserare dinamică DKI',
    outputFormat: 'Format de ieșire (JSON):',
    strictFormat: 'Vă rugăm să urmați strict formatul JSON și să asigurați 15 titluri.'
  },

  'Malay': {
    intro: 'Anda adalah penulis iklan Google Ads profesional. Berdasarkan maklumat produk berikut, hasilkan 15 tajuk iklan carian Google.',
    productInfo: 'Maklumat Produk:',
    productName: 'Nama Produk',
    brand: 'Jenama',
    unknown: 'Tidak diketahui',
    rating: 'Penilaian',
    reviews: 'ulasan',
    aboutItem: 'Tentang item ini',
    features: 'Ciri-ciri Produk',
    notProvided: 'Tidak disediakan',
    keywords: 'Kata kunci volum tinggi:',
    searchVolume: 'Volum Carian',
    requirements: 'Keperluan:',
    req1: '1. Hasilkan 15 tajuk, setiap satu maksimum 30 aksara (termasuk ruang)',
    req2: '2. 3 tajuk pertama mesti memasukkan nama jenama dan nama produk utama (contoh, "Teslong Inspection Camera")',
    req3: '3. 5 tajuk di tengah harus memasukkan kata kunci volum tinggi',
    req4: '4. 7 tajuk terakhir harus menekankan ciri-ciri produk, manfaat, promosi',
    req5: '5. Gunakan bahasa dengan niat pembelian tinggi (beli, kedai, rasmi, diskaun, promosi, dll.)',
    req6: '6. Elakkan menggunakan sintaks sisipan dinamik DKI',
    outputFormat: 'Format Output (JSON):',
    strictFormat: 'Sila ikuti format JSON dengan ketat dan pastikan 15 tajuk.'
  }
}

export const DESCRIPTION_LANGUAGE_INSTRUCTIONS: Record<string, LanguageInstructionSet> = HEADLINE_LANGUAGE_INSTRUCTIONS

/**
 * 获取标题生成的语言指令
 */
export function getHeadlineLanguageInstructions(targetLanguage: string): LanguageInstructionSet {
  return HEADLINE_LANGUAGE_INSTRUCTIONS[targetLanguage] || HEADLINE_LANGUAGE_INSTRUCTIONS['English']
}

/**
 * 获取描述生成的语言指令
 */
export function getDescriptionLanguageInstructions(targetLanguage: string): LanguageInstructionSet {
  return DESCRIPTION_LANGUAGE_INSTRUCTIONS[targetLanguage] || DESCRIPTION_LANGUAGE_INSTRUCTIONS['English']
}
