import {
  applyYeahPromosTemplateSiteId,
  assertPartnerboostAsinRequestLimit,
  buildComparableUrlTokens,
  buildYeahPromosDeltaScopePlan,
  buildYeahPromosProductsPageUrl,
  calculateExponentialBackoffDelay,
  detectYeahPromosHttpIntercept,
  extractAsinFromUrlLike,
  extractPartnerboostLinkId,
  isPartnerboostRateLimited,
  isPartnerboostRateLimitError,
  isPartnerboostTransientError,
  isYeahPromosRateLimited,
  isYeahPromosTransientError,
  parseYeahPromosProxyCountryUrlMap,
  resolveOfferProductBackfillDecision,
  resolvePartnerboostFullSyncCountrySequence,
  resolveSyncMaxPages,
  resolveYeahPromosMarketplaceTemplates,
  resolveYeahPromosProxyProviderUrl,
} from './parsing'
import {
  buildYeahPromosAdvertContentUrl,
  normalizeYeahPromosStoreMerchant,
  parseYeahPromosProductHtmlPage,
  resolveYeahPromosConsecutiveFailureStrategy,
  resolveYeahPromosProductMid,
  resolveYeahPromosSyncSessionMinRemainingMs,
} from './platform-fetch'
import { dedupeNormalizedProducts } from './upsert'
import { mapAffiliateProductRow, normalizeNumericRangeBounds } from './query'

export const __testOnly = {
  assertPartnerboostAsinRequestLimit,
  calculateExponentialBackoffDelay,
  buildComparableUrlTokens,
  dedupeNormalizedProducts,
  extractAsinFromUrlLike,
  extractPartnerboostLinkId,
  isPartnerboostTransientError,
  isPartnerboostRateLimited,
  isPartnerboostRateLimitError,
  isYeahPromosRateLimited,
  isYeahPromosTransientError,
  parseYeahPromosProductHtmlPage,
  buildYeahPromosProductsPageUrl,
  applyYeahPromosTemplateSiteId,
  buildYeahPromosDeltaScopePlan,
  resolveYeahPromosMarketplaceTemplates,
  resolveYeahPromosSyncSessionMinRemainingMs,
  resolveYeahPromosConsecutiveFailureStrategy,
  parseYeahPromosProxyCountryUrlMap,
  resolveYeahPromosProxyProviderUrl,
  detectYeahPromosHttpIntercept,
  resolveYeahPromosProductMid,
  normalizeYeahPromosStoreMerchant,
  buildYeahPromosAdvertContentUrl,
  resolveOfferProductBackfillDecision,
  resolvePartnerboostFullSyncCountrySequence,
  normalizeNumericRangeBounds,
  mapAffiliateProductRow,
  resolveSyncMaxPages,
}
