export const TOP_HEADLINE_SLOT_START_INDEX = 1

export const TOP_HEADLINE_SLOT_COUNT = 3

export const TOP_HEADLINE_MAX_LENGTH = 30

export const TOP_HEADLINE_SEMANTIC_DUPLICATE_THRESHOLD = 0.78

export const RETAINED_KEYWORD_HEADLINE_SLOT_START_INDEX = 4

export const RETAINED_KEYWORD_HEADLINE_SLOT_COUNT = 3

export const RETAINED_KEYWORD_DESCRIPTION_SLOT_START_INDEX = 0

export const RETAINED_KEYWORD_DESCRIPTION_SLOT_COUNT = 2

export const RETAINED_KEYWORD_HEADLINE_MAX_LENGTH = 30

export const RETAINED_KEYWORD_DESCRIPTION_MAX_LENGTH = 90

export const RETAINED_KEYWORD_PROTECTED_HEADLINE_COUNT = 4

export const RETAINED_KEYWORD_PROTECTED_SIMILARITY_THRESHOLD = 0.82

export const GOOGLE_ADS_HEADLINE_UNIQUENESS_SUFFIXES = [
  'Now',
  'Today',
  'Deals',
  'Official',
  'Shop',
] as const
